---

- name: 'Check icat-lucene package'
  stat:
    path: /home/{{ payara_user }}/downloads/icat.lucene-{{ icat_lucene_version }}-distro.zip
  register: packageResult

- name: 'Download icat-lucene'
  get_url:
    url: https://repo.icatproject.org/repo/org/icatproject/icat.lucene/{{ icat_lucene_version }}/icat.lucene-{{ icat_lucene_version }}-distro.zip
    dest: /home/{{ payara_user }}/downloads
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0664
  when: packageResult.stat.exists is defined and packageResult.stat.exists == false

- name: 'Unarchive icat-lucene if not installed'
  unarchive:
    src: /home/{{ payara_user }}/downloads/icat.lucene-{{ icat_lucene_version }}-distro.zip
    dest: /home/{{ payara_user }}/install
    remote_src: true
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
  when: ansible_local.local.instantiations.icat_lucene is not defined or ansible_local.local.versions.icat_lucene != icat_lucene_version

- name: "Find any war files not matching the current version"
  find:
    paths: /home/{{ payara_user }}/install/icat.lucene/
    use_regex: yes
    patterns: "^.*-(?!{{ icat_lucene_version }}).*\\.war$"
  register: warFilesResult

- name: "Remove war files not matching the current version"
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ warFilesResult.files }}"

- name: 'Configure icat-lucene setup.properties'
  template:
    src: roles/payara/templates/setup.properties.j2
    dest: /home/{{ payara_user }}/install/icat.lucene/setup.properties
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0600
  notify:
  - "icat-lucene-handler"

- name: 'Configure icat-lucene run.properties'
  template:
    src: templates/run.properties.j2
    dest: /home/{{ payara_user }}/install/icat.lucene/run.properties
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0664
  notify:
  - "icat-lucene-handler"

- name: 'Create icat-lucene data directory'
  file:
    path: /home/{{ payara_user }}/data/lucene
    state: directory
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0775

- name: 'Configure icat-lucene logback.xml'
  copy:
    src: files/logback.xml
    dest: /home/{{ payara_user }}/install/icat.lucene/logback.xml
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
    mode: 0664
  notify:
  - "icat-lucene-handler"

- name: 'Setup icat-lucene if not setup'
  import_tasks: tasks/installation.yml
  when: (ansible_local is not defined) or (ansible_local.local is not defined) or (ansible_local.local.instantiations is not defined) or (ansible_local.local.instantiations.icat_lucene is not defined) or (ansible_local.local.instantiations.icat_lucene != 'true')
